### ISSUE TITLE
A working example could be nice

### ISSUE THREAD

**Issue by ahallora** [schmuli/atom-less#12]
Hi. Nice plugin. However, I can't get it working with autoprefix and browserlist.... A working example could be nice. How do you actually use it in Atom? 😄

**Comment by ahallora** [comment]
Never mind... 😉 

I got it working with:

- [x] [less-autocompile](https://atom.io/packages/less-autocompile),
- [x] [atom-minify](https://atom.io/packages/atom-minify) (minify on save), and
- [x] [autoprefixer](https://atom.io/packages/autoprefixer) (manually executed on the minified css).

My less-file has this ```less-autocompile``` setup:
```CSS
// out: style.min.css, sourcemap: false, compress: true

@awesomeLessVaraible: #ff0055;

body {
    background-color: @awesomeLessVaraible;
    transform: translate3d(0,0,0);
}
```

Just in case others want to make Less, Minify, Compress and Autoprefixer happen with [Atom](https://atom.io/). 👍  😄
